config/routes.rb
Rails.application.routes.draw do
  root "top#index"

  resources :users, only: [:index, :show]
  resources :weight_histories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_many :weight_histories
end

app/models/weight_history.rb
class WeightHistory < ApplicationRecord
  belongs_to :user

  before_validation :set_memo

  validates :user_id, presence: { message: "ユーザを入力してください"}
  validates :memo, length: { maximum: 255, too_long: "メモは最大%{count}文字以内で入力してください" }
  validate :weight_validate #カスタムのバリデーションはvalidatesではなくてvalidate

  def weight_validate
    if weight < 1
      errors.add(:weight, "体重が正しくありません")
    end
  end

  def set_memo
    if memo.nil?
      #modelの中で代入するときはselfが必要
      #memo = "なし"だと代入はできていないことになる
      self.memo = "なし"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        # viewに対して情報を渡すために@をつける
        @user = User.find(params["id"])
    end
end

app/controllers/weight_histories_controller.rb
class WeightHistoriesController < ApplicationController
  before_action :set_weight_history, only: %i[ show edit update destroy ]

  # GET /weight_histories or /weight_histories.json
  def index
    @weight_histories = WeightHistory.all
  end

  # GET /weight_histories/1 or /weight_histories/1.json
  def show
  end

  # GET /weight_histories/new
  def new
    @weight_history = WeightHistory.new
  end

  # GET /weight_histories/1/edit
  def edit
  end

  # POST /weight_histories or /weight_histories.json
  def create
    @weight_history = WeightHistory.new(weight_history_params)

    if @weight_history.save
      redirect_to weight_history_url(@weight_history), notice: "Weight history was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /weight_histories/1 or /weight_histories/1.json
  def update
    respond_to do |format|
      if @weight_history.update(weight_history_params)
        format.html { redirect_to weight_history_url(@weight_history), notice: "Weight history was successfully updated." }
        format.json { render :show, status: :ok, location: @weight_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @weight_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weight_histories/1 or /weight_histories/1.json
  def destroy
    @weight_history.destroy!

    respond_to do |format|
      format.html { redirect_to weight_histories_url, notice: "Weight history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight_history
      @weight_history = WeightHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def weight_history_params
      params.require(:weight_history).permit(:user_id, :weight, :memo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weight_histories_helper.rb
module WeightHistoriesHelper
    def weight_comment(weight)
        if weight < 20
            "#{weight} {痩せ型}"
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTutorial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<h1>Hello</h1>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<% @users.each do |user| %>
  <%= link_to user.name, user_path(user) %><br>
<% end %>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>

<%= @user.name %><br>
<%= @user.age %>才<br>

<%= link_to "一覧画面に戻る", users_path %>

app/views/weight_histories/_form.html.erb
<%= form_with(model: weight_history) do |form| %>
  <% if weight_history.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(weight_history.errors.count, "error") %> prohibited this weight_history from being saved:</h2>

      <ul>
        <% weight_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.number_field :weight %>
  </div>

  <div>
    <%= form.label :memo, style: "display: block" %>
    <%= form.text_field :memo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/weight_histories/_weight_history.html.erb
<div id="<%= dom_id weight_history %>">
  <p>
    <strong>User:</strong>
    <%= weight_history.user.name %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= weight_comment(@weight_history.weight) %>
  </p>

  <p>
    <strong>Memo:</strong>
    <%= weight_history.memo %>
  </p>

</div>

app/views/weight_histories/edit.html.erb
<h1>Editing weight history</h1>

<%= render "form", weight_history: @weight_history %>

<br>

<div>
  <%= link_to "Show this weight history", @weight_history %> |
  <%= link_to "Back to weight histories", weight_histories_path %>
</div>

app/views/weight_histories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Weight histories</h1>

<div id="weight_histories">
  <% @weight_histories.each do |weight_history| %>
    <%= render weight_history %>
    <p>
      <%= link_to "Show this weight history", weight_history %>
    </p>
  <% end %>
</div>

<%= link_to "New weight history", new_weight_history_path %>

app/views/weight_histories/new.html.erb
<h1>New weight history</h1>

<%= render "form", weight_history: @weight_history %>

<br>

<div>
  <%= link_to "Back to weight histories", weight_histories_path %>
</div>

app/views/weight_histories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @weight_history %>

<div>
  <%= link_to "Edit this weight history", edit_weight_history_path(@weight_history) %> |
  <%= link_to "Back to weight histories", weight_histories_path %>

  <%= button_to "Destroy this weight history", @weight_history, method: :delete %>
</div>